site_name: Doc

theme:
  name: material

nav:
    - Home: 'index.md'
    - JavaScript:
        - 'misc': 'javascript/misc.md'
        - training:
            - chapter02:
                - '06-install-environnement': 'javascript/training/chapter02/06-install-environnement.md'
                - '08-install-babel': 'javascript/training/chapter02/08-install-babel.md'
                - '09-javascript-in-html': 'javascript/training/chapter02/09-javascript-in-html.md'
    - MkDocs:
        - 'MkDocs - Misc': 'mkdocs/mkdocs.md'
    - Git:
        - 'Git - Misc': 'git/git.md'
    - ElasticSearch:
        - 'ElasticSearch - Misc': 'elasticsearch/elasticsearch.md'
    - IntelliJ:
        - 'IntelliJ - 01 - Misc': 'intellij/1-intellij-misc.md'
        - 'IntelliJ - 02 - WSL': 'intellij/2-intellij-wsl.md'
    - Linux:
        - 'Linux - 01 - Misc': 'linux/1-linux-misc.md'
    - Docker:
        - 'Docker - 01 - Misc': 'docker/1-docker-misc.md'
        - 'Docker - 02 - Basis': 'docker/2-docker-basis.md'
        - 'Docker - 03 - Docker File': 'docker/3-docker-dockerfile.md'
        - 'Docker - 04 - Docker Hub': 'docker/4-docker-dockerhub.md'
        - 'Docker - 05 - Node Server': 'docker/5-docker-nodeserver.md'
        - 'Docker - 06 - Data Persistence': 'docker/6-docker-datapersistence.md'
        - 'Docker - 07 - Network': 'docker/7-docker-network.md'
        - 'Compose - 08 - Use': 'docker/8-compose-use.md'
        - 'Compose - 09 - Dockerfile': 'docker/9-compose-dockerfile.md'
        - 'Compose - 10 - Services': 'docker/10-compose-services.md'
        - 'Compose - 11 - Production': 'docker/11-compose-production.md'
    - VS Code:
        - 'VS Code - Misc': 'vscode/vscode.md'
    - Windows:
        - 'Windows - Misc': 'windows/windows.md'
    - MongoDB:
        - 'MongoDB - Misc': 'mongodb/mongodb.md'
    - Redis:
        - 'Redis - 01 - Misc': 'redis/1-redis-misc.md'
    - Agile Methodology:
        - 'Agile Methodology - 01 - Misc': 'agilemethodology/1-agilemethodology-misc.md'
    - Kafka:
        - 'Kafka - 01 - Misc': 'kafka/1-kafka-misc.md'

# $ mkdocs build
# $ mkdocs gh-deploy
