site_name: Doc

theme:
  name: material

nav:
    - Home: 'index.md'
    - MkDocs:
        - 'MkDocs - Misc': 'mkdocs/mkdocs.md'
    - Git:
        - 'Git - Misc': 'git/git.md'
    - ElasticSearch:
        - 'ElasticSearch - Misc': 'elasticsearch/elasticsearch.md'
    - Intellij:
        - 'Intellij - Misc': 'intellij/intellij.md'
    - Linux:
        - 'Linux - Misc': 'linux/linux.md'
    - Docker:
        - 'Docker - Misc': 'docker/0-docker-misc.md'
        - 'Docker - Basis': 'docker/1-docker-basis.md'
        - 'Docker - Dockerfile': 'docker/2-docker-dockerfile.md'
        - 'Docker - Docker Hub': 'docker/3-docker-dockerhub.md'
        - 'Docker - Node Server Image': 'docker/4-docker-nodeserverimage.md'
    - VS Code:
        - 'VS Code - Misc': 'vscode/vscode.md'
    - Windows:
        - 'Windows - Misc': 'windows/windows.md'


# $ mkdocs build
# $ mkdocs gh-deploy
